name: Build for MacOS

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: macos-latest
    name: Build on macOS
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Install NodeJS Dependencies
        run: npm install

      - name: Build Boringtun
        run: npm run build:boringtun

      - name: Build
        run: npm run build:mac

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-m1-artifacts
          path: ./build/mac/boringtunjs.node

