name: Building Boringtunjs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Boringtunjs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact-name: "linux"
            build-script: "npm run build:linux"
          - os: macos-14
            artifact-name: "mac_m"
            build-script: "npm run build:mac_m"
          #              - os: macos-latest  # todo
          #                build-script: "npm run build:mac_intel"
          #              - os: windows-latest # todo
          #                build-script: "npm run build:win"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: actions-rs/toolchain@v2
        with:
          toolchain: stable
          default: true

      - name: Install NodeJS Dependencies
        run: npm install

      - name: Build Boringtun ${{ matrix.artifact-name }}
        run: npm run build:boringtun

      - name: Build
        run: ${{ matrix.build-script }}

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-artifacts }}
          path: ./build/${{ matrix.artifact-name }}/boringtunjs.node

