name: Building Boringtun.JS

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Building Boringtun.JS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        include:
          - os: ubuntu-20.04
            process_platform: "linux"
            process_arch: "x64"
            node: 20
          - os: macos-14
            process_platform: "darwin"
            process_arch: "arm64"
            node: 20

          # todo: - os: macos-latest
          # todo: - os: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Rust
        # https://github.com/rust-lang/rustup/issues/3409
        uses: dtolnay/rust-toolchain@master # https://github.com/dtolnay/rust-toolchain
        with:
          toolchain: stable

      - name: Build Boringtun
        run: npm run build:boringtun

      - name: Install NodeJS Dependencies
        run: npm install

      - name: Build boringtunjs bindings
        run: npm run build

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: boringtunjs-${{ github.ref_name }}-${{ matrix.node }}-${{ matrix.process_platform }}-${{ matrix.process_arch }}
          path: ./build/boringtunjs.node

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4 # https://github.com/actions/download-artifact
      - name: Rename Artifacts
        run: |
          mv ./boringtunjs-${{ github.ref_name }}-20-linux-x64/boringtunjs.node ./boringtunjs-${{ github.ref_name }}-20-linux-x64.node
          mv ./boringtunjs-${{ github.ref_name }}-20-darwin-arm64/boringtunjs.node ./boringtunjs-${{ github.ref_name }}-20-darwin-arm64.node
      - name: Create Release
        uses: ncipollo/release-action@v1 # https://github.com/ncipollo/release-action
        with:
          name: Boringtun.JS release ${{ github.ref_name }}
          artifacts: "./boringtunjs-*.node"
          # example for downloading
          # https://github.com/boringjs/boringtun.js/releases/download/v0.0.13/boringtunjs-v0.0.13-20-darwin-arm64.node

  npm-publish:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}